# sets variables $(TestDataUrl)

parameters:
  TestDataUrl: https://ortinternaltestdata.blob.core.windows.net/models/20191122.zip

steps:
- task: CmdLine@1
  displayName: 'Set TestDataUrl variable'
  inputs:
    filename: echo
    arguments: '##vso[task.setvariable variable=TestDataUrl;]${{parameters.TestDataUrl}}'
